### ISSUE TITLE
Peer Review: Parastoook

### ISSUE THREAD

**Issue by asford** [UWSEDS-aut17/uwseds-group-group-by#3]
# Group Peer Review

As a "group" peer review, review the team's progress toward developing a functional specification [homework 5](https://github.com/UWSEDS/hw5-aut17) and component design [homework 6](https://github.com/UWSEDS/hw6-aut17).

The team should have a discoverable functional specification with:

- [x] A target user/consumer profile.
- [x] A problem statement.
- [x] A list of 2-3 cases.

The should also provide a general including:

- [x] A list of 3-4 components.
- [x] Component names.
- [x] A component purpose
- [x] Component inputs and outputs.
- [x] Pseudocode for design.

**Comment by Parastoook** [comment]
Sorry I just find the invitation mail to review your homework but I think I found everything on the Rubric in your files. 8/8 nice work.
