### ISSUE TITLE
Peer Review: JunlinLi30

### ISSUE THREAD

**Issue by asford** [UWSEDS-aut17/uwseds-group-group-by#5]
# Group Peer Review

As a "group" peer review, review the team's progress toward developing a functional specification [homework 5](https://github.com/UWSEDS/hw5-aut17) and component design [homework 6](https://github.com/UWSEDS/hw6-aut17).

The team should have a discoverable functional specification with:

- [x] A target user/consumer profile.
- [x] A problem statement.
- [x] A list of 2-3 cases.

The should also provide a general including:

- [x] A list of 3-4 components.
- [x] Component names.
- [x] A component purpose
- [x] Component inputs and outputs.
- [x] Pseudocode for design.

**Comment by JunlinLi30** [comment]
I thought there should be checkboxes like before but apparently, there isn't. 
**Nice job!** I'm impressed by how you guy structured this repo and all the things look **well-organized, straightforward and clear**. Good luck on tomorrow's presentation! Looking forward to it!
If I should give points, then **full score**! (8/8, supposed one point for each)
